# install.yml
#
# ­­­
- hosts: app-servers
  gather_facts: true
  become: true
  tasks:
  - name: install tomcat
    package:
      name: tomcat7
  - name: start / enable tomcat
    service:
           name: tomcat7
           enabled: true
           state: started
  - name: wait for tomcat to start and up on port 8080
    wait_for:
            port: 8080
  - name: ensure home page returns 200
    uri: 
        url: http://127.0.0.1:8080
- hosts: load-balancers
  gather_facts: true
  become: true
  tasks:
  - name : install Haproxy
    package:
      name: haproxy
  - name: allow service to start
    lineinfile:
      dest: /etc/default/haproxy
      regexp: ENABLED=.*
      line: ENABLED=1
  - name: Install configuration file
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: start/enable haproxy
    service:
      name: haproxy
      enabled: true
      state: started
